server:
  port: 8080
spring:
  profiles: dev
---
server:
  port: 8081
spring:
  profiles: test

---
server:
  port: 8082
spring:
  profiles: pro

---

spring:
  profiles:
    active: test

  datasource:
    url: jdbc:oracle:thin:@192.168.80.10:1521:orcl
    username: wateruser
    password: itcast
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

mybatis-plus:
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类路径
  type-aliases-package: com.example.aoptest.entity
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    # 数据库字段驼峰下划线转换
    db-column-underline: true
    # id自增类型(数据库id自增)
    id-type: 0